/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "5% of water production is turned into a scaling multiplier on production": "5% 的水产量转化为产量的缩放倍数",
    "The statue of liberty is made from 179,000 pounds of copper, thats alot of copper! If you did the math it would take approximately 1e130 fire to melt it, so get working and dont think of getting any pesky water or earth (which are disabled)": "自由女神像由 179,000 磅铜制成，这可是大量的铜！ 如果你算了一下，大约需要 1e130 火才能融化它，所以开始工作吧，不要想着得到任何讨厌的水或土（这是禁用的）",
    "\"Listen, you're going to die in a year and I'm not sure there's much you can do about it\" The doctor says": "“听着，一年后你就会死去，我不确定你能做些什么”医生说",
    "(Aether)": "（醚）",
    "(because idk you might miss out on some good Walmart sale or something)": "（因为我不知道你可能会错过一些好的沃尔玛促销或其他东西）",
    "(Energy Multiplier)": "（能量倍增器）",
    "(Log1.25(space + 1), next poiint at": "(Log1.25(空格 + 1)，下一点位于",
    "(Log1.5(air + 1), next point at": "(Log1.5(气 + 1)，下一点在",
    "(Log10(fire + 1), next point at": "(Log10(火 + 1)，下一点在",
    "(Log2(earth + 1), next point at": "(Log2(土 + 1)，下一点在",
    "(Log4(water + 1), next point at": "(Log4(水 + 1)，下一点在",
    "(The key and sucess to a healthy eternal life)": "（健康永生的关键与成功）",
    "% Chance to increase production every tick": "每个刻度增加产量的机会百分比",
    "% Filled": "％ 填充时",
    "1 (Base energy)": "1（基础能量）",
    "1: Lead (Symbol ♄)": "1：铅（符号 ♄）",
    "2: Tin (Symbol ♃)": "2：锡（符号 ♃）",
    "3: Iron (Symbol ♂)": "3：铁（符号 ♂）",
    "4: Silver (Symbol ☽)": "4：银（符号 ☽）",
    "5: Copper (Symbol ♀)": "5：铜（符号 ♀）",
    "6: Quicksilver (Symbol ☿)": "6：水银（符号 ☿）",
    "7: Gold (Symbol ☼)": "7：黄金（符号 ☼）",
    "Aether": "醚",
    "Aether Generator": "以太发生器",
    "Air amount no longer resets on resets": "重置时空气量不再重置",
    "Air Generator": "空气发生器",
    "Air, giving a": "空气，给予",
    "All basic autobuyer unlocked and 2x upgrades are autobought": "所有基本自动购买器均已解锁，2x 升级均为自动购买",
    "All values are set to their max across all resets": "所有值在所有重置中均设置为最大值",
    "Arid Production": "干旱生产",
    "Autobuyer buys a fire generator every tick": "自动购买器每 tick 都会购买一台火灾发生器",
    "Autobuyer buys a water generator every tick": "自动购买器每 tick 都会购买一台制水机",
    "Autobuyer buys an earth generator every tick": "自动购买器 每 tick 都会购买一台土生成器",
    "Big Shoutouts to Jakub, incremental_gamer, Liniarc, and everyone from the Incremental Game Jam community who helped test this": "向 Jakub、incremental_gamer、Liniarc 以及来自 Incremental Game Jam 社区中帮助测试此功能的每个人表示大力支持",
    "Blazing Inferno": "炽热地狱",
    "Buy Max": "购买最大",
    "Challengers": "挑战者",
    "Challenges": "挑战",
    "Challenges puts you in a modified run with everything reset except a reduced energy multiplier based on your current multiplier": "挑战会让你进入修改后的运行模式，除了根据当前乘数减少能量乘数外，一切都会重置",
    "Combine all your matter to get closer to the stone!": "结合你所有的物质来更接近石头！",
    "Condensor": "冷凝器",
    "Continue": "继续",
    "Copy your save file!": "复制你的保存文件！",
    "Cost:": "成本：",
    "Current": "当前",
    "Current Highest:": "当前最高：",
    "Current:": "当前：",
    "Current: /": "当前： /",
    "Currnet: ^": "当前网络：^",
    "Damn I should really get the philosophers stone": "该死，我真的应该得到贤者之石",
    "Dirt^2": "污垢^2",
    "Divide Cost of Earth Generator by Water Generator Count + 1": "将土生成器的成本除以水生成器数量 + 1",
    "earth": "土",
    "Earth": "土",
    "Earth Generator": "土生成器",
    "energy": "能量",
    "Energy": "能量",
    "Energy (Increasing highest for challenge 4 has no affect)": "能量（挑战 4 增加最高值没有影响）",
    "Energy (Increasing highest for challenge 7 has no affect)": "能量（挑战 7 增加最高值没有影响）",
    "Explosiveness": "爆发力",
    "Export Game to Clipboard": "将游戏存档导出到剪贴板",
    "Export Game to File": "将游戏存档导出到文件",
    "Exports are saved to your clipboard and downloaded as a file!": "导出内容将保存到您的剪贴板并作为文件下载！",
    "Fanning it out": "将其扇形展开",
    "Final Challenge: Energy mult is square rooted, all production is square rooted aswell": "最终挑战：能量乘数是平方根，所有生产也是平方根",
    "fire": "火",
    "Fire": "火",
    "Fire Generator": "火生成器",
    "Flameburst": "烈焰爆发",
    "Flameburst happens multiple time per tick and can stack": "烈焰爆发每 tick 会发生多次并且可以叠加",
    "Flameburst II": "烈焰爆发 II",
    "Flameburst III": "烈焰爆发 III",
    "Fluidic Flow": "流体流动",
    "Formula": "公式",
    "Frequent Flamer": "频繁喷火",
    "Gain a multiplier that grows with gametime": "获得随游戏时间而增长的乘数",
    "Gain a reset multiplier based on time in current reset": "根据当前复位时间获得复位乘数",
    "Gain multiplier based on fire count": "基于火数的增益乘数",
    "Gain water production multiplier equal to Water Generator Count + 1": "获得水产量乘数等于水发生器数量 + 1",
    "Generator": "生成器",
    "Generators": "生成器",
    "Geomagnetic": "地磁",
    "Hearth Home": "壁炉之家",
    "Hosed Down": "用水管冲洗",
    "Hydroburst": "水爆",
    "Ignition Burst": "点火爆裂",
    "Import Game": "导入游戏",
    "Import your save:": "导入你的保存：",
    "Increase Flamebursts Production Multiplier": "增加烈焰爆发产量倍数",
    "Increase output of fire generators by 250%": "火灾发生器输出量增加 250%",
    "Increase production based on total generator count": "根据生成器总数增加产量",
    "Lead melts at 621 degrees Farenheit, thats quite hot already! Get to a certain water goal without using fire to cool it down.": "铅在 621 华氏度时熔化，已经很热了！ 无需使用火来冷却即可达到特定的水目标。",
    "Multiplier based on amount of water upgrades purchased": "基于购买的水升级数量的乘数",
    "Multiplier that falls based on time in current reset": "根据当前重置中的时间下降的乘数",
    "Multiplier to generator contributing most to energy": "对能量贡献最大的生成器乘数",
    "Multiply Earth Gain by 2x": "将土增益乘以 2 倍",
    "Multiply Effective Water Generator count by 5": "将有效水生成器数量乘以 5",
    "Multiply Fire Gain by 2x": "将火增益乘以 2 倍",
    "Multiply water Gain by 2x": "将水增益乘以 2 倍",
    "No one likes Tin, maybe we can bury it in dirt and forget about it, reach a certain earth amount with the other elements disabled because we need to focus on burying tin": "没有人喜欢锡，也许我们可以把它埋在泥土里然后忘记它，在禁用其他元素的情况下达到一定的土量，因为我们需要专注于埋锡",
    "Now you have nothing to lose, you can do anything you wanted in life, but all you really wanted is to live like 2 more years": "现在你已经没有什么可失去的了，你可以做任何你想做的事情，但你真正想要的只是再活两年",
    "Nutrient Rich": "营养丰富",
    "Philosophers": "贤者",
    "Philosophers Stone": "贤者之石",
    "Primoridal Flood": "原始洪水",
    "Quicksilver is named for its speed, but surely you can do faster, get to an energy goal within 2 minutes or Quick silver rapidly halts production": "Quicksilver 因其速度而得名，但您当然可以做得更快，在 2 分钟内达到能量目标，否则 Quick silver 会迅速停止生产",
    "Raise earth production to an exponent": "将土产量提高到指数级",
    "Reset everything, but keep your energy and get an energy mult": "重置一切，但保持能量并获得能量倍增",
    "Reset Game": "重置游戏",
    "RESET GAME?": "重置游戏？",
    "Reset!": "重置！",
    "Reward: Earth Production Multiplier based on Earth Generator Amount and Highest Earth in this Challenge (": "奖励：基于土生成器数量和本次挑战中最高土的土生产乘数（",
    "Reward: Energy Multiplier formula improved (energyMult^": "奖励：改进能量乘数公式（energyMult^",
    "Reward: Fire Generators^": "奖励：火焰发生器^",
    "Reward: Giant scaling multiplier based on time played (": "奖励：基于游戏时间的巨大缩放乘数（",
    "Reward: Unlock Aether generator, generating pure energy": "奖励：解锁以太发生器，产生纯净能量",
    "Reward: Unlock Space Generators, generating all generators of basic types": "奖励：解锁空间生成器，生成所有基本类型的生成器",
    "Reward: Water Generator Effective count ^ (": "奖励：水生成器有效次数^(",
    "Robot Takeover": "机器人接管",
    "Silver has a halflife of 439 years, but just for you we can accelerate it to 1 minute! Production is halved every 20 seconds after the first minute": "银的半衰期为 439 年，但我们可以为您将其加速到 1 分钟！ 第一分钟后每 20 秒产量减半",
    "So it seems that you're going to have to Automate the Philosophers Stone (In your basement)": "所以看来你必须自动化贤者之石（在你的地下室）",
    "Space Generator": "空间发生器",
    "Space, adding +": "空格，添加+",
    "Stable Growth": "稳定增长",
    "Start Challenge": "开始挑战",
    "Story": "故事",
    "Submit": "提交",
    "Surge": "浪涌",
    "Terraform": "地形",
    "Terraquake": "地震",
    "Thanks so much for playing!": "非常感谢您的参与！",
    "The problem is you know you're really lazy and dont want to go through all the work": "问题是你知道你真的很懒并且不想完成所有的工作",
    "time": "时间",
    "to every generator amount": "每个生成器数量",
    "Unlock all row 2 elemental upgrades (9 more)": "解锁所有第 2 行元素升级（另外 9 个）",
    "Unlock challenges, difficult adventures with great rewards!": "解锁挑战、艰难的冒险并获得丰厚的奖励！",
    "Unlocks at": "解锁于",
    "Unlocks the air generator!": "解锁空气发生器！",
    "unspent Energy": "未使用的能量",
    "Upgrade!!": "升级！！",
    "Upgrades": "升级",
    "Vapor Vortex": "蒸气涡流",
    "water": "水",
    "Water": "水",
    "Water Generator": "水发生器",
    "x Energy": "x 能量",
    "x Multiplier to all previous generators": "x 所有先前生成器的乘数",
    "You are in": "你在",
    "You automated the Philosopher Stone!": "你自动化了贤者石！",
    "You can exit challenges at any time to come back to your current save": "您可以随时退出挑战以返回当前保存",
    "You cant make steel without iron and you know what really has been a steal? These shop prices! Shop prices are doubled": "没有铁就无法炼钢，你知道什么才是真正的偷窃吗？ 这些店的价格！ 商店价格翻倍",
    "You get a random call out of the blue from your doctor and he gives you the bad news": "您突然接到医生的电话，他告诉您坏消息",
    "You have been in this challenge for": "您参加这项挑战已经有",
    "You instantly have an idea! You've read books about Alchemy before and think to youself": "你立刻就有想法了！ 你以前读过有关炼金术的书并自己思考",
    "You need to enable JavaScript to run this app.": "您需要启用 JavaScript 才能运行此应用程序。",
    "Your reward for a challenge is based on your highest achievable value for a certain element that you are aiming for the in the challenge": "您的挑战奖励取决于您在挑战中针对特定元素可实现的最高价值",
    "times": "次",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Challenge ": "挑战",
    "(Currently: ": "(当前: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) seconds$/, '$1 秒'],
    [/^([\d\.,]+) minutes, and ([\d\.,]+) seconds$/, '$1 分，$2 秒'],
    [/^([\d\.,]+) hours, and ([\d\.,]+) seconds$/, '$1 小时，$2 秒'],
    [/^([\d\.,]+) hours, ([\d\.,]+) minutes, and ([\d\.,]+) seconds$/, '$1 小时，$2 分，$3秒'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Goal: (.+) Energy$/, '目标：$1 能量'],
    [/^Goal: (.+) Fire$/, '目标：$1 火'],
    [/^Goal: (.+) Water$/, '目标：$1 水'],
    [/^Goal: (.+) Earth$/, '目标：$1 土'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);